FROM debian:10-slim as builder
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y python3-pip python3-setuptools python3-dev make gcc\
 && apt-get clean && rm -rf /var/lib/apt/lists/*
ADD requirements-dev.txt /tmp/
RUN pip3 install wheel && pip3 install -r /tmp/requirements-dev.txt
RUN mkdir /app
ADD . /app
RUN cd app && python3 -m pytest -v --capture=no tests/